### ISSUE TITLE
Set MSRV to 1.53

### ISSUE THREAD

**Issue by brainstorm** [popzxc/stdext-rs#14]
Otherwise, it breaks like so: https://github.com/rust-lang/rfcs/pull/2818#issuecomment-873815977

**Comment by popzxc** [comment]
Thanks for creating this issue! Totally forgot to do it.

Note that if you need this crate to work with the `rustc` 1.52 or older, it's possible to use v0.2 (which also has the macro for getting function name, but is not bound on the recent compiler).
